// Generated by CoffeeScript 1.6.3
(function() {
  var connectionCount, http, listenPort, onm, scdlAddressNewCatalogue, scdlAddressRoot, scdlModel, scdlStore;

  http = require('http');

  onm = require('onm');

  scdlModel = new onm.Model(require('onmd-scdl').DataModel);

  scdlStore = new onm.Store(scdlModel);

  scdlAddressRoot = scdlModel.createRootAddress();

  scdlAddressNewCatalogue = scdlModel.createPathAddress("scdl.catalogues.catalogue");

  listenPort = process.env.OPENSHIFT_NODEJS_PORT || 1031;

  connectionCount = 0;

  console.log("onm data store service started.");

  console.log("... listening for connections on port " + listenPort);

  http.createServer(function(req, res) {
    var catalogueNamespace, reqAgent, reqHost;
    reqAgent = req.headers['user-agent'];
    reqHost = req.headers['host'];
    console.log("" + (connectionCount++) + ": " + reqHost + " via " + reqAgent);
    res.writeHead(200, {
      'Content-Type': 'text/json'
    });
    catalogueNamespace = scdlStore.createComponent(scdlAddressNewCatalogue);
    res.end(scdlStore.toJSON());
    console.log(catalogueNamespace.toJSON());
    console.log("---");
    console.log("---");
    return scdlStore.removeComponent(catalogueNamespace.getResolvedAddress());
  }).listen(listenPort);

}).call(this);
