// Generated by CoffeeScript 1.6.3
(function() {
  var http, onm, scdlAddressNewCatalogue, scdlAddressRoot, scdlModel, scdlStore;

  http = require('http');

  onm = require('onm');

  scdlModel = new onm.Model(require('onmd-scdl').DataModel);

  scdlStore = new onm.Store(scdlModel);

  scdlAddressRoot = scdlModel.createRootAddress();

  scdlAddressNewCatalogue = scdlModel.createPathAddress("scdl.catalogues.catalogue");

  http.createServer(function(req, res) {
    var catalogueNamespace;
    res.writeHead(200, {
      'Content-Type': 'text/json'
    });
    catalogueNamespace = scdlStore.createComponent(scdlAddressNewCatalogue);
    res.end(scdlStore.toJSON());
    console.log(catalogueNamespace.toJSON(void 0, 2));
    return scdlStore.removeComponent(catalogueNamespace.getResolvedAddress());
  }).listen(1031);

}).call(this);
